### ISSUE TITLE
How to get the ckpt

### ISSUE THREAD

**Issue by coding-sharks** [fauxneticien/fastconformer_standalone#1]
i do not find the ckpt file in the repo...tmp/nemo_unpacked/model_weights.ckpt

**Comment by fauxneticien** [comment]
@coding-sharks  — you can fetch the pre-trained weights from the HF repo: https://huggingface.co/nvidia/stt_en_fastconformer_ctc_large/blob/main/stt_en_fastconformer_ctc_large.nemo.

NeMo files are just tar files so you can download and untar to get the `.ckpt` file inside them.

```bash
cd tmp
wget https://huggingface.co/nvidia/stt_en_fastconformer_ctc_large/resolve/main/stt_en_fastconformer_ctc_large.nemo
mkdir nemo_unpacked
tar -xvf stt_en_fastconformer_ctc_large.nemo -C nemo_unpacked
```

**Comment by coding-sharks** [comment]
@fauxneticien Many thanks! honestly, i am not familiar to .nemo... Thanks for your information!
